[package]
name = "silverlining"
version = "0.1.0"
edition = "2018"

[dependencies]
clipboard = "0.5.0"
fasteval = "0.2.4"
glium = "0.30.2"
image = "0.24.4"
imgui = { version = "0.8.2", features = ["tables-api"] }
imgui-glium-renderer = "0.8.2"
imgui-winit-support = "0.8.2"
